name: Build Windows x64 (.exe) - Qt6 MSVC

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-win64-msvc:
    runs-on: windows-latest
    env:
      QT_VERSION: 6.9.2
      QT_ARCH: win64_msvc2022_64
      QT_DIR: C:\Qt

    steps:
      - uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          pip install aqtinstall
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --no-progress
          choco install ninja --no-progress

      - name: Install Qt (MSVC 2022 x64)
        shell: pwsh
        run: |
          python -m aqt install-qt windows desktop $env:QT_VERSION $env:QT_ARCH --outputdir $env:QT_DIR

      - name: Configure (CMake + Ninja)
        shell: pwsh
        run: |
          $env:CMAKE_PREFIX_PATH = "C:\Qt\$env:QT_VERSION\msvc2022_64"
          cmake -S . -B build -G "Ninja" -DCMAKE_PREFIX_PATH="$env:CMAKE_PREFIX_PATH"

      - name: Build (Release)
        run: cmake --build build --config Release

      - name: Deploy Qt runtime (windeployqt)
        shell: pwsh
        run: |
          $qtbin = "C:\Qt\$env:QT_VERSION\msvc2022_64\bin"
          $exe   = "build\helloqt.exe"     # 若你的 exe 在 build\Release\，改那個路徑
          & "$qtbin\windeployqt.exe" --release --compiler-runtime "$exe"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HelloQt-Windows-x64
          path: build/**/*
